Change bashtickets dir structure

diff --git a/bin/bashtickets b/bin/bashtickets
--- a/bin/bashtickets
+++ b/bin/bashtickets
@@ -1,57 +1,75 @@
 #!/bin/bash
 
-# -------------
-# Sanity checks
-# -------------
-
-# Define a useful 'error' utility function, and make it available to subcommands
-# (libstderred.so compatible -- see https://unix.stackexchange.com/a/164223)
-error () { awk "BEGIN { print \"$*\" > \"/dev/stderr\" }"; }
-export -f error
-
-
-# Assert everything is installed in the expected locations (relative to this script)
-export BT_BIN_DIR="$(dirname "$BASH_SOURCE" | xargs realpath)"
-export BT_ROOT_DIR="${BT_BIN_DIR%"/bin"}"
-export BT_BIN_DIR="${BT_ROOT_DIR/bin}"
-export BT_DOC_DIR="$BT_ROOT_DIR/doc"
-export BT_SHARE_DIR="$BT_ROOT_DIR/share"
-export BT_TEMPLATES_DIR="$BT_SHARE_DIR/templates"
-export BT_UTILS_DIR="$BT_SHARE_DIR/utils"
-
-if     test -d "$BT_ROOT_DIR"      &&
-       test -d "$BT_BIN_DIR"       &&
-       test -d "$BT_DOC_DIR"       &&
-       test -d "$BT_SHARE_DIR"     &&
-       test -d "$BT_TEMPLATES_DIR" &&
-       test -d "$BT_UTILS_DIR"
-
-then   :   # i.e. do nothing
-
-else   error "Error: did not detect a valid installation of bashtickets."
-       error "Please re-install and try again."
-       exit 1
-fi
+################################################################################
+###
+### Bashtickets v0.0.1
+###
+### Code sections in this file:
+###
+### - Script constants
+###   - Bashticket directories
+###   - Error codes
+### - Function definitions
+###   - Helper functions
+###     - error
+###     - trycatch
+###     - check_bashtickets_installation
+###     - check_repo
+###     - load_config
+###   - Bashticket Commands
+###     - initialise_bashtickets_repository
+### - Main body
+###   - Perform initial sanity checks
+###   - Execute bashtickets command
+###
+################################################################################
 
 
 
-# -------------------------------------
-# Define helper constants and functions
-# -------------------------------------
+####################
+### Script constants
+####################
 
-# Exit statuses for various errors
-declare -i EXIT_STATUS__INVALID_BASHTICKETS_INSTALLATION=1
-declare -i EXIT_STATUS__NOT_A_VALID_BASHTICKETS_REPOSITORY=2
-declare -i EXIT_STATUS__FAILED_TO_INITIALIZE_REPOSITORY=3
-declare -i EXIT_STATUS__FAILED_TO_CREATE_TICKET_OR_MILESTONE=4
-declare -i EXIT_STATUS__FAILED_TO_CREATE_TICKET=5
-declare -i EXIT_STATUS__FAILED_TO_CREATE_MILESTONE=6
-declare -i EXIT_STATUS__FAILED_TO_CLOSE_TICKET=7
-declare -i EXIT_STATUS__FAILED_TO_REOPEN_TICKET=8
-declare -i EXIT_STATUS__FAILED_TO_ADD_COMMENT_TO_TICKET=9
-declare -i EXIT_STATUS__FAILED_TO_ASSIGN_TICKETS_TO_MILESTONE=10
+# Declare directories where relevant bashticket files should reside
+BT_BIN_DIR="$(dirname "$BASH_SOURCE" | xargs realpath)"
+BT_ROOT_DIR="${BT_BIN_DIR%"/bin"}"
+BT_BIN_DIR="${BT_ROOT_DIR/bin}"
+BT_SHARE_DIR="$BT_ROOT_DIR/share"
+BT_DOC_DIR="$BT_SHARE_DIR/doc"
 
-declare -i EXIT_STATUS__CALLED_WITHOUT_SUBCOMMAND=100
+# Declare exit statuses for various errors
+declare -i EXIT_STATUS__INVALID_BASHTICKETS_INSTALLATION=2
+declare -i EXIT_STATUS__NOT_A_VALID_BASHTICKETS_REPOSITORY=3
+declare -i EXIT_STATUS__FAILED_TO_INITIALIZE_REPOSITORY=4
+declare -i EXIT_STATUS__FAILED_TO_CREATE_TICKET_OR_MILESTONE=5
+declare -i EXIT_STATUS__FAILED_TO_CREATE_TICKET=6
+declare -i EXIT_STATUS__FAILED_TO_CREATE_MILESTONE=7
+declare -i EXIT_STATUS__FAILED_TO_CLOSE_TICKET=8
+declare -i EXIT_STATUS__FAILED_TO_REOPEN_TICKET=9
+declare -i EXIT_STATUS__FAILED_TO_ADD_COMMENT_TO_TICKET=10
+declare -i EXIT_STATUS__FAILED_TO_ASSIGN_TICKETS_TO_MILESTONE=11
+
+declare -i EXIST_STATUS__INVALID_SUBCOMMAND=100
+
+
+
+########################
+### Function definitions
+########################
+
+# ----------------
+# Helper functions
+# ----------------
+
+function error () {
+# A useful, 'libstderred.so' compatible function for safely echoing error
+# messages to stderr (see: https://unix.stackexchange.com/a/164223)
+
+    awk "BEGIN { print \"$*\" > \"/dev/stderr\" }"
+}
+
+
+
 
 function trycatch () {
 
@@ -60,25 +78,147 @@ function trycatch () {
 
     declare -i EXITSTATUS="${@: -1}"              # Get last input argument only
 
-    if   "$BT_UTILS_DIR/${COMMAND[@]}"   # Run the respective BT utility command
-                                         # given as the first argument, with
-                                         # remaining arguments passed
-                                         # appropriately
+    if   "${COMMAND[@]}"   # Run the respective command with accompanying
+                           # arguments
+
     then :
+
     else exit $EXITSTATUS   # If the above command exited with non-zero status,
                             # abort this script with the exit status provided as
                             # the last input argument to this function
     fi
 }
 
-# helper functions
-function check_repo    () { trycatch "is_valid_bashtickets_repository" $EXIT_STATUS__NOT_A_VALID_BASHTICKETS_REPOSITORY && export CONFIG_FILE="$( realpath ./.bashtickets/config )"; }
-function display_help  () { echo "Showing help... TODO"; exit 0; }
-function display_usage () { echo "Displaying usage ... TODO"; exit $EXIT_STATUS__CALLED_WITHOUT_SUBCOMMAND; }
 
-# ---------------------
-# Parse input arguments
-# ---------------------
+
+
+function check_bashtickets_installation () {
+
+  # Assert everything is installed in the expected locations (relative to this script)
+    if     test -d "$BT_ROOT_DIR"      &&
+           test -d "$BT_BIN_DIR"       &&
+           test -d "$BT_SHARE_DIR"     &&
+           test -d "$BT_DOC_DIR"
+
+    then   :   # i.e. do nothing
+
+    else   error "Error: did not detect a valid installation of bashtickets."
+           error "Please re-install and try again."
+           return 1
+    fi
+}
+
+
+
+function check_repo () {
+
+    trycatch "is_valid_bashtickets_repository" \
+             $EXIT_STATUS__NOT_A_VALID_BASHTICKETS_REPOSITORY
+}
+
+
+
+
+function load_config () {
+
+    CONFIG_FILE="$( realpath ./.bashtickets/config )"
+    source "$CONFIG_FILE"
+}
+
+
+
+
+function display_usage () { echo "Displaying usage ... TODO"; exit $EXIST_STATUS__INVALID_SUBCOMMAND; }
+
+
+# -------------------
+# Bashticket commands
+# -------------------
+
+function initialise_bashtickets_repository () {
+
+  # Ensure this command was called with no arguments
+    if   test ${#@} -gt 0
+    then "display_usage"
+         return 1
+    fi
+
+  # Desired case: Empty directory detected
+    if     test $( ls -A | wc -l ) -eq 0   # empty directory detected
+
+    then   if     mkdir .bashtickets
+
+           then   :
+
+           else   error "Error: Could not create a '.bashtickets' subdirectory in the current directory."
+                  error "       Please ensure you have the necessary permissions."
+                  return 1
+           fi
+
+
+           if   cp  "$BT_DOC_DIR/sample_config" ".bashtickets/config"
+
+           then :
+
+           else   error "Error: Could not create a 'config' file in the '.bashtickets' subdirectory."
+                  error "       Please ensure you have the necessary permissions."
+                  return 1
+           fi
+
+
+           if     mkdir tickets
+
+           then   :
+
+           else   error "Error: Could not create 'tickets' directory."
+                  return 1
+           fi
+
+
+           if     mkdir milestones
+
+           then   :
+
+           else   error "Error: Could not create 'milestones' directory."
+                  return 1
+           fi
+
+           echo   "Bashtickets repository initialised successfully."
+
+    elif   "$BT_UTILS_DIR/is_valid_bashtickets_repository" 2> /dev/null
+
+    then   error "Error: Current directory is already a valid bashtickets repository"
+           error "       Aborting..."
+           return 1
+
+    else   error "Error: Non-empty directory detected."
+           error "       To initialise as a bashtickets repository, please delete all files"
+           error "       (including hidden files) and try again."
+           return 1
+    fi
+}
+
+
+
+
+function display_help  () { echo "Showing help... TODO"; exit 0; }
+
+
+
+#############
+### Main body
+#############
+
+# -----------------------------
+# Perform initial sanity checks
+# -----------------------------
+
+trycatch "check_bashtickets_installation" $EXIT_STATUS__INVALID_BASHTICKETS_INSTALLATION
+trycatch "check_repo" $EXIT_STATUS__NOT_A_VALID_BASHTICKETS_REPOSITORY
+
+# ---------------------------
+# Execute bashtickets command
+# ---------------------------
 
 case "$1" in
     ("init")                             trycatch "initialise_bashtickets_repository" $EXIT_STATUS__FAILED_TO_INITIALIZE_REPOSITORY ;;
