Added optional header to show_closed_tickets_by_milestone

diff --git a/bin/bashtickets b/bin/bashtickets
--- a/bin/bashtickets
+++ b/bin/bashtickets
@@ -1634,13 +1634,42 @@
     # If the number is "0", this will reflect 'unmilestoned' tickets.
     # --------------------------------------------------------------------------
 
-    # If called without arguments or with more than one arguments, display usage
-      if   test "$#" -ne 1
-      then display_usage "show_closed_tickets_by_milestone"
+      local HEADER
+      local HEADERLINE
+      local TICKET
+      local TICKETNAME
+      local TICKETSUMMARY
+      local MILESTONE
+      local -a MILESTONE_TICKETS
+
+    # Process input arguments
+      local -A OPTIONS
+      local -a ARGS
+      local VALID_SHORT_FLAG_OPTIONS=( )
+      local VALID_LONG_FLAG_OPTIONS=( )
+      local VALID_SHORT_FLAG_OPTIONS=( -H )
+      local VALID_LONG_FLAG_OPTIONS=( --header )
+      local COMMAND_NAME="show_closed_tickets_by_milestone"
+
+      if   process_optargs "$@"
+      then :
+      else exit $EXIT_STATUS__INVALID_SUBCOMMAND_SYNTAX
+      fi
+
+    # Validate input arguments
+      if   is_in '-H'       "${!OPTIONS[@]}"; then HEADER="On"
+      elif is_in '--header' "${!OPTIONS[@]}"; then HEADER="On"
+      fi
+
+      if   test ${#ARGS[@]} -eq 1   # If called without arguments or with more than one arguments, display usage
+      then :
+      else error "Error: Incorrect arguments provided to show_closed_tickets_by_milestone"
+           echo && display_usage "show_closed_tickets_by_milestone"
            exit $EXIT_STATUS__INVALID_SUBCOMMAND_SYNTAX
       fi
 
-      local MILESTONE="${1%.milestone}"
+
+      local MILESTONE="${ARGS[0]%.milestone}"
 
       if   test "$MILESTONE" = "0"
       then MILESTONE=""
@@ -1653,12 +1682,17 @@
 
       cd "$TICKETS_PATH"
 
+      if   test "$HEADER" = "On"
+      then HEADERLINE="Closed tickets for milestone $MILESTONE"
+           echo -e "${ANSI_BLUE}${ANSI_BOLD_ON}${HEADERLINE}${ANSI_BOLD_OFF}${ANSI_RESET}"
+           printf "${ANSI_BLUE}${ANSI_BOLD_ON}%${#HEADERLINE}s${ANSI_BOLD_OFF}${ANSI_RESET}\n" "" | tr ' ' '='   # place an appropriate number of '=' chars to underline the HEADERLINE
+      fi
 
-      local MILESTONE_TICKETS=( $(egrep --color=never  -l "Milestone: $MILESTONE\$" *.ticket) )
+      MILESTONE_TICKETS=( $(egrep --color=never  -l "Milestone: $MILESTONE\$" *.ticket) )
 
       for  TICKET in "${MILESTONE_TICKETS[@]}"
-      do   local TICKETNAME="$(grep -l --color=never 'Open/Closed: Closed' "$TICKET")"
-           local TICKETSUMMARY="$(grep --color=never "Summary: " "$TICKET")"
+      do   TICKETNAME="$(grep -l --color=never 'Open/Closed: Closed' "$TICKET")"
+           TICKETSUMMARY="$(grep --color=never "Summary: " "$TICKET")"
            if test -n "$TICKETNAME"
            then echo "$TICKETNAME $TICKETSUMMARY"
            fi
@@ -2279,7 +2313,8 @@
          "remove"        | "reopen"        | "rm"            | "sh"  | \
          "show"          | "st"            | "status"        | "up"  | \
          "update"        | "view"          | "vm"            | "vt"  | \
-         "show_open_tickets_by_milestone" \
+         "show_open_tickets_by_milestone" |\
+         "show_closed_tickets_by_milestone" \
        )
 
            trycatch "check_repo" \
