Add ability to assign parent milestone to nt and nm

diff --git a/bin/bashtickets b/bin/bashtickets
--- a/bin/bashtickets
+++ b/bin/bashtickets
@@ -439,16 +439,53 @@ function new_ticket_or_milestone () {
 
 
 function new_ticket () {
-    if   test ${#@} -gt 0
-    then error "Error: Incorrect arguments provided to new_ticket function"
-         echo
-         display_usage
-         return 1
+
+    local PARENT_MILESTONE
+    local PARENT_MILESTONE_NUM
+    local PARENT_FILESTONE_FILE
+    local LAST_TICKET_NUM
+    local NEW_TICKET_NUM
+    local NEW_TICKET_FILE
+    local UNEDITED_TICKET
+    local EDITED_TICKET
+
+
+  # Check if a parent milestone has been specified (and generally if the command
+  # was called with correct syntax)
+    if   test ${#@} -eq 0                               # no arguments provided
+    then :
+
+    elif test ${#@} -eq 1 && test "${1:0:2}" = "-m"          # e.q. -m1
+    then PARENT_MILESTONE="${1:2}"
+
+    elif test ${#@} -eq 2 && test "$1" = "-m"                # e.g. -m 1
+    then PARENT_MILESTONE="$2"
+
+    elif test ${#@} -eq 1 && test "${1:0:12}" = "--milestone="   # e.g. --milestone=1
+    then PARENT_MILESTONE="${1:12}"
+
+    elif test ${#@} -eq 2 && test "$1" = "--milestone"          # e.g. --milestone 1
+    then PARENT_MILESTONE="$2"
+
+    else error "Error: Incorrect arguments provided to new_ticket function"
+         echo && display_usage
+         exit $EXIT_STATUS__INVALID_SUBCOMMAND_SYNTAX
     fi
 
 
     cd $TICKETS_PATH
 
+
+  # If a parent milestone has been specified, check that this is valid
+  # before proceeding
+    if   test -n "$PARENT_MILESTONE"
+    then PARENT_MILESTONE_FILE="${PARENT_MILESTONE%.milestone}.milestone"
+         if   is_valid_milestone "$PARENT_MILESTONE"
+         then PARENT_MILESTONE_NUM="${PARENT_MILESTONE_FILE%.milestone}"
+         else error "The specified parent milestone ('$PARENT_MILESTONE_FILE') does not exist in $MILESTONES_PATH. Aborting."
+              return 1
+         fi
+    fi
 
   # If this is the first ticket, start numbering from 1; otherwise, find the
    # last ticket number, and increment by one.
@@ -501,6 +538,9 @@ function new_ticket () {
     done
     declare +i REPLY
 
+  # Set the provided parent milestone, if one was provided
+    sed -i "s/Milestone: /Milestone: $PARENT_MILESTONE_NUM/" "${NEW_TICKET_FILE}"
+
   # Set today's date
     TODAY=$(date +"%Y-%m-%d")
     sed -i "s/Date: /Date: $TODAY/" "${NEW_TICKET_FILE}"
@@ -533,16 +573,53 @@ function new_ticket () {
 
 function new_milestone () {
 
-  if   test ${#@} -gt 0
-  then error "Error: Incorrect arguments provided to new_milestone function"
-       echo
-       display_usage
-       return 1
+local PARENT_MILESTONE
+local PARENT_MILESTONE_NUM
+local PARENT_FILESTONE_FILE
+local LAST_MILESTONE_NUM
+local NEW_MILESTONE_NUM
+local NEW_MILESTONE_FILE
+local DEFAULT_STARTDATE
+local DEFAULT_DEADLINE
+local UNEDITED_MILESTONE
+local EDITED_MILESTONE
+
+# Check if a parent milestone has been specified (and generally if the command
+# was called with correct syntax)
+  if   test ${#@} -eq 0                               # no arguments provided
+  then :
+
+  elif test ${#@} -eq 1 && test "${1:0:2}" = "-p"          # e.q. -p1
+  then PARENT_MILESTONE="${1:2}"
+
+  elif test ${#@} -eq 2 && test "$1" = "-p"                # e.g. -p 1
+  then PARENT_MILESTONE="$2"
+
+  elif test ${#@} -eq 1 && test "${1:0:9}" = "--parent="   # e.g. --parent=1
+  then PARENT_MILESTONE="${1:9}"
+
+  elif test ${#@} -eq 2 && test "$1" = "--parent"          # e.g. --parent 1
+  then PARENT_MILESTONE="$2"
+
+  else error "Error: Incorrect arguments provided to new_milestone function"
+       echo && display_usage
+       exit $EXIT_STATUS__INVALID_SUBCOMMAND_SYNTAX
   fi
 
 # Capture milestones path and template onto the relevant variables
 
   cd $MILESTONES_PATH
+
+# If a parent milestone has been specified, check that this is valid
+# before proceeding
+  if   test -n "$PARENT_MILESTONE"
+  then PARENT_MILESTONE_FILE="${PARENT_MILESTONE%.milestone}.milestone"
+       if   is_valid_milestone "$PARENT_MILESTONE"
+       then PARENT_MILESTONE_NUM="${PARENT_MILESTONE_FILE%.milestone}"
+       else error "The specified parent milestone ('$PARENT_MILESTONE_FILE') does not exist in $MILESTONES_PATH. Aborting."
+            return 1
+       fi
+  fi
 
 # If this is the first milestone, start numbering from 1; otherwise, find the
  # last milestone number, and increment by one.
@@ -566,6 +643,9 @@ function new_milestone () {
   DEFAULT_STARTDATE="$(get_default_milestone_startdate)"
   sed -i "s/Startdate: /Startdate: $DEFAULT_STARTDATE/" "${NEW_MILESTONE_FILE}"
 
+# Update parent (milestone) node number
+  sed -i "s/Parent Node: /Parent Node: $PARENT_MILESTONE_NUM/" "${NEW_MILESTONE_FILE}"
+
 # Set deadline from default
   DEFAULT_DEADLINE="$( get_default_milestone_deadline $DEFAULT_STARTDATE )"
   sed -i "s/Deadline: /Deadline: $DEFAULT_DEADLINE/" "${NEW_MILESTONE_FILE}"
@@ -575,7 +655,7 @@ function new_milestone () {
 
 # Open the resulting file for editing (see 'editor' function), placing the cursor
 # at the Title field.
-  editor "${NEW_MILESTONE_FILE}" 2 16
+  editor "${NEW_MILESTONE_FILE}" 3 16
 
   EDITED_MILESTONE="$(cat $NEW_MILESTONE_FILE)"
 
