Harmonized formatting

diff --git a/share/utils/add_comment_to_ticket b/share/utils/add_comment_to_ticket
--- a/share/utils/add_comment_to_ticket
+++ b/share/utils/add_comment_to_ticket
@@ -2,6 +2,13 @@
 
 # Usage: add_comment_to_ticket <ticket number>   # e.g. 023
 
+  if   test ${#@} -ne 1
+  then error "Error: Incorrect arguments provided to new_milestone function"
+       echo
+       "$BT_UTILS_DIR/display_usage"
+       exit 1
+  fi
+
   # Ensure script is initial-path agnostic
     TICKETS_PATH="$( dirname $BASH_SOURCE )"
     TICKETS_PATH="$TICKETS_PATH/tickets"
diff --git a/share/utils/assign_tickets_to_milestone b/share/utils/assign_tickets_to_milestone
--- a/share/utils/assign_tickets_to_milestone
+++ b/share/utils/assign_tickets_to_milestone
@@ -1,62 +1,62 @@
 #!/bin/bash
 
 # If called without arguments, display usage
-if   test "$#" -le 1
-then echo "Usage:"
-     echo "    $(basename $0) <ticket> [<ticket2> <ticket3> ... <ticketN>] <milestone>"
-     echo
-     echo "e.g.:"
-     echo "    $(basename $0) 001.ticket 002.ticket 001.milestone"
-     echo
-     echo "or simply:"
-     echo "    $(basename $0) 001 002 001"
-     echo
-     echo "Note: Using '0' as the milestone removes any existing milestones from the specified tickets instead"
-     exit
-fi
+  if   test "$#" -le 1
+  then echo "Usage:"
+       echo "    $(basename $0) <ticket> [<ticket2> <ticket3> ... <ticketN>] <milestone>"
+       echo
+       echo "e.g.:"
+       echo "    $(basename $0) 001.ticket 002.ticket 001.milestone"
+       echo
+       echo "or simply:"
+       echo "    $(basename $0) 001 002 001"
+       echo
+       echo "Note: Using '0' as the milestone removes any existing milestones from the specified tickets instead"
+       exit
+  fi
 
 # Process Input Arguments
-ARGS=( "$@" )                               # Get all positional arguments as a bash array
-MILESTONE_ARG="${ARGS[-1]}"                 # Get the last element of the array
-TICKET_ARGS=( "${ARGS[@]: 0 : $# - 1 }" )   # Create a sub-array, from index 0 to N-1
+  ARGS=( "$@" )                               # Get all positional arguments as a bash array
+  MILESTONE_ARG="${ARGS[-1]}"                 # Get the last element of the array
+  TICKET_ARGS=( "${ARGS[@]: 0 : $# - 1 }" )   # Create a sub-array, from index 0 to N-1
 
 # Obtain relevant absolute paths
-BASHTICKETS_PATH="$( dirname $BASH_SOURCE | xargs realpath )"
-TICKETS_PATH="$BASHTICKETS_PATH/tickets"
-MILESTONES_PATH="$BASHTICKETS_PATH/milestones"
+  BASHTICKETS_PATH="$( dirname $BASH_SOURCE | xargs realpath )"
+  TICKETS_PATH="$BASHTICKETS_PATH/tickets"
+  MILESTONES_PATH="$BASHTICKETS_PATH/milestones"
 
 # Confirm validity of inputs
-ERRORS=0
+  ERRORS=0
 
-for  TICKET_ARG in "${TICKET_ARGS[@]}"
-do   if   test -f "$TICKETS_PATH/${TICKET_ARG%.ticket}.ticket"
-     then :
-     else echo "Input Error: No such ticket (${TICKET_ARG%.ticket}.ticket) exists in $TICKETS_PATH"
-          ERRORS=$((ERRORS + 1))
-     fi
-done
+  for  TICKET_ARG in "${TICKET_ARGS[@]}"
+  do   if   test -f "$TICKETS_PATH/${TICKET_ARG%.ticket}.ticket"
+       then :
+       else echo "Input Error: No such ticket (${TICKET_ARG%.ticket}.ticket) exists in $TICKETS_PATH"
+            ERRORS=$((ERRORS + 1))
+       fi
+  done
 
-if   test -f "$MILESTONES_PATH/${MILESTONE_ARG%.milestone}.milestone"
-then :
-else echo "Input Error: No such milestone (${MILESTONE_ARG%.milestone}.milestone) exists in $MILESTONES_PATH"
-     ERRORS=$((ERRORS + 1))
-fi
+  if   test -f "$MILESTONES_PATH/${MILESTONE_ARG%.milestone}.milestone"
+  then :
+  else echo "Input Error: No such milestone (${MILESTONE_ARG%.milestone}.milestone) exists in $MILESTONES_PATH"
+       ERRORS=$((ERRORS + 1))
+  fi
 
-if test "$ERRORS" -gt 0
-then echo "Encountered $ERRORS input errors. Aborting."
-     exit 1
-fi
+  if test "$ERRORS" -gt 0
+  then echo "Encountered $ERRORS input errors. Aborting."
+       exit 1
+  fi
 
 # Process all tickets
-MILESTONE_NO="${MILESTONE_ARG%.milestone}"   # Remove .milestone suffix
-MILESTONE_NO="${MILESTONE_NO%0}"           # If milestone was '0', use empty string instead.
-MILESTONE_FILE="$MILESTONES_PATH/${MILESTONE_ARG%.milestone}.milestone"
+  MILESTONE_NO="${MILESTONE_ARG%.milestone}"   # Remove .milestone suffix
+  MILESTONE_NO="${MILESTONE_NO%0}"           # If milestone was '0', use empty string instead.
+  MILESTONE_FILE="$MILESTONES_PATH/${MILESTONE_ARG%.milestone}.milestone"
 
-for  TICKET_ARG in "${TICKET_ARGS[@]}"
-do   TICKET_NO="${TICKET_ARG%.ticket}"
-     TICKET_FILE="$TICKETS_PATH/${TICKET_ARG%.ticket}.ticket"
-     sed -i "s/  Milestone: .*\$/  Milestone: ${MILESTONE_NO}/" "$TICKET_FILE"
-done
+  for  TICKET_ARG in "${TICKET_ARGS[@]}"
+  do   TICKET_NO="${TICKET_ARG%.ticket}"
+       TICKET_FILE="$TICKETS_PATH/${TICKET_ARG%.ticket}.ticket"
+       sed -i "s/  Milestone: .*\$/  Milestone: ${MILESTONE_NO}/" "$TICKET_FILE"
+  done
 
 # update milestones accordingly - note, we need to update ALL milestones, because more than one may have changed
-"$BASHTICKETS_PATH/update_milestones"
+  "$BASHTICKETS_PATH/update_milestones"
diff --git a/share/utils/close_ticket_with_comment b/share/utils/close_ticket_with_comment
--- a/share/utils/close_ticket_with_comment
+++ b/share/utils/close_ticket_with_comment
@@ -2,12 +2,12 @@
 
 # Usage: close_ticket_with_comment <ticket number>   # e.g. 023
 
-if   test ${#@} -ne 1
-then error "Error: Incorrect arguments provided to new_milestone function"
-     echo
-     "$BT_UTILS_DIR/display_usage"
-     exit 1
-fi
+  if   test ${#@} -ne 1
+  then error "Error: Incorrect arguments provided to new_milestone function"
+       echo
+       "$BT_UTILS_DIR/display_usage"
+       exit 1
+  fi
 
 ## Note: the 'error' function used here is defined in the main bashtickets
   # script and exported here
diff --git a/share/utils/initialise_bashtickets_repository b/share/utils/initialise_bashtickets_repository
--- a/share/utils/initialise_bashtickets_repository
+++ b/share/utils/initialise_bashtickets_repository
@@ -1,63 +1,63 @@
 #!/bin/bash
 
 # Note: the 'error' function used here is defined in the main bashtickets script
-# and exported here
+ # and exported here
 
-if   test ${#@} -gt 0
-then "$BT_UTILS_DIR/display_usage"
-     exit 1
-fi
-
-
-if     test $( ls -A | wc -l ) -eq 0   # empty directory detected
-
-then   if     mkdir .bashtickets
-
-       then   :
-
-       else   error "Error: Could not create a '.bashtickets' subdirectory in the current directory."
-              error "       Please ensure you have the necessary permissions."
-              exit 1
-       fi
-
-
-       if   cp  "$BT_DOC_DIR/sample_config" ".bashtickets/config"
-
-       then :
-
-       else   error "Error: Could not create a 'config' file in the '.bashtickets' subdirectory."
-              error "       Please ensure you have the necessary permissions."
-              exit 1
-       fi
-
-
-       if     mkdir tickets
-
-       then   :
-
-       else   error "Error: Could not create 'tickets' directory."
-              exit 1
-       fi
-
-
-       if     mkdir milestones
-
-       then   :
-
-       else   error "Error: Could not create 'milestones' directory."
-              exit 1
-       fi
-
-       echo   "Bashtickets repository initialised successfully."
-
-elif   "$BT_UTILS_DIR/is_valid_bashtickets_repository" 2> /dev/null
-
-then   error "Error: Current directory is already a valid bashtickets repository"
-       error "       Aborting..."
+  if   test ${#@} -gt 0
+  then "$BT_UTILS_DIR/display_usage"
        exit 1
+  fi
 
-else   error "Error: Non-empty directory detected."
-       error "       To initialise as a bashtickets repository, please delete all files"
-       error "       (including hidden files) and try again."
-       exit 1
-fi
+
+  if     test $( ls -A | wc -l ) -eq 0   # empty directory detected
+
+  then   if     mkdir .bashtickets
+
+         then   :
+
+         else   error "Error: Could not create a '.bashtickets' subdirectory in the current directory."
+                error "       Please ensure you have the necessary permissions."
+                exit 1
+         fi
+
+
+         if   cp  "$BT_DOC_DIR/sample_config" ".bashtickets/config"
+
+         then :
+
+         else   error "Error: Could not create a 'config' file in the '.bashtickets' subdirectory."
+                error "       Please ensure you have the necessary permissions."
+                exit 1
+         fi
+
+
+         if     mkdir tickets
+
+         then   :
+
+         else   error "Error: Could not create 'tickets' directory."
+                exit 1
+         fi
+
+
+         if     mkdir milestones
+
+         then   :
+
+         else   error "Error: Could not create 'milestones' directory."
+                exit 1
+         fi
+
+         echo   "Bashtickets repository initialised successfully."
+
+  elif   "$BT_UTILS_DIR/is_valid_bashtickets_repository" 2> /dev/null
+
+  then   error "Error: Current directory is already a valid bashtickets repository"
+         error "       Aborting..."
+         exit 1
+
+  else   error "Error: Non-empty directory detected."
+         error "       To initialise as a bashtickets repository, please delete all files"
+         error "       (including hidden files) and try again."
+         exit 1
+  fi
diff --git a/share/utils/new_milestone b/share/utils/new_milestone
--- a/share/utils/new_milestone
+++ b/share/utils/new_milestone
@@ -1,17 +1,17 @@
 #!/bin/bash
 
-## Note: the 'error' function used here is defined in the main bashtickets
-  # script and exported here
+# Note: the 'error' function used here is defined in the main bashtickets
+ # script and exported here
 
-if   test ${#@} -gt 0
-then error "Error: Incorrect arguments provided to new_milestone function"
-     echo
-     "$BT_UTILS_DIR/display_usage"
-     exit 1
-fi
+  if   test ${#@} -gt 0
+  then error "Error: Incorrect arguments provided to new_milestone function"
+       echo
+       "$BT_UTILS_DIR/display_usage"
+       exit 1
+  fi
 
-## Note: no 'valid repo' sanity checks here, since they will have been already
-  # performed by the main 'bashtickets' executable
+# Note: no 'valid repo' sanity checks here, since they will have been already
+ # performed by the main 'bashtickets' executable
 
 # 'Import' arrays defined in config
   source "$CONFIG_FILE"
@@ -22,8 +22,9 @@ fi
 
   cd $MILESTONES_PATH
 
-## If this is the first milestone, start numbering from 1; otherwise, find the
-  # last milestone number, and increment by one.
+# If this is the first milestone, start numbering from 1; otherwise, find the
+ # last milestone number, and increment by one.
+
   if     test -f 1.milestone
   then   LAST_MILESTONE_NUM=$(ls *.milestone | sort -n | tail -n -1)   # list files, sort in numerical (not alphabetical) order, and keep last filename
          LAST_MILESTONE_NUM=${LAST_MILESTONE_NUM%.milestone}   # parameter expansion: remove '.milestone' suffix
diff --git a/share/utils/new_ticket b/share/utils/new_ticket
--- a/share/utils/new_ticket
+++ b/share/utils/new_ticket
@@ -1,17 +1,17 @@
 #!/bin/bash
 
 # Note: the 'error' function used here is defined in the main bashtickets script
-# and exported here
+ # and exported here
 
-if   test ${#@} -gt 0
-then error "Error: Incorrect arguments provided to new_ticket function"
-     echo
-     "$BT_UTILS_DIR/display_usage"
-     exit 1
-fi
+  if   test ${#@} -gt 0
+  then error "Error: Incorrect arguments provided to new_ticket function"
+       echo
+       "$BT_UTILS_DIR/display_usage"
+       exit 1
+  fi
 
 # Note: no 'valid repo' sanity checks here, since they will have been already
-# performed by the main 'bashtickets' executable
+ # performed by the main 'bashtickets' executable
 
 # 'Import' arrays defined in config
   source "$CONFIG_FILE"
@@ -22,8 +22,10 @@ fi
 
   cd $TICKETS_PATH
 
+
 # If this is the first ticket, start numbering from 1; otherwise, find the
-# last ticket number, and increment by one.
+ # last ticket number, and increment by one.
+
   if     test -f 1.ticket
   then   LAST_TICKET_NUM=$(ls *.ticket | sort -n | tail -n -1)   # list files, sort in numerical (not alphabetical) order, and keep last filename
          LAST_TICKET_NUM=${LAST_TICKET_NUM%.ticket}   # parameter expansion: remove '.ticket' suffix
@@ -70,10 +72,11 @@ fi
   sed -i "s/Status: /Status: Open/" "${NEW_TICKET_FILE}"
 
 # Open resulting file in the user's editor of choice, as detected by the
-# EDITOR environmental variable. This can be overriden per bashtickets
-# repository, by assigning to this variable in the repository's config file
-# instead. If the EDITOR variable is not defined at all, nano is used as the
-# default editor.
+ # EDITOR environmental variable. This can be overriden per bashtickets
+  # repository, by assigning to this variable in the repository's config file
+  # instead. If the EDITOR variable is not defined at all, nano is used as the
+  # default editor.
+
   if   test $EDITOR = "vim"
   then vim '+cal cursor(2,14)' "${NEW_TICKET_FILE}"
   else nano +2,14 "${NEW_TICKET_FILE}"
diff --git a/share/utils/show_closed_tickets_by_milestone b/share/utils/show_closed_tickets_by_milestone
--- a/share/utils/show_closed_tickets_by_milestone
+++ b/share/utils/show_closed_tickets_by_milestone
@@ -1,50 +1,50 @@
 #!/bin/bash
 
 # If called without arguments or with more than one arguments, display usage
-if   test "$#" -ne 1 || test "$1" = "--help" | test "$1" = "-h"
-then echo "Usage:"
-     echo "    $(basename $0) <milestone>"
-     echo
-     echo "e.g.:"
-     echo "    $(basename $0) 001.milestone"
-     echo
-     echo "or simply:"
-     echo "    $(basename $0) 001"
-     echo
-     echo "Note: Using '0' as the milestone displays tickets that are not assigned to any milestones"
-     exit
-fi
+  if   test "$#" -ne 1 || test "$1" = "--help" | test "$1" = "-h"
+  then echo "Usage:"
+       echo "    $(basename $0) <milestone>"
+       echo
+       echo "e.g.:"
+       echo "    $(basename $0) 001.milestone"
+       echo
+       echo "or simply:"
+       echo "    $(basename $0) 001"
+       echo
+       echo "Note: Using '0' as the milestone displays tickets that are not assigned to any milestones"
+       exit
+  fi
 
 # Obtain relevant absolute paths
-BASHTICKETS_PATH="$( dirname $BASH_SOURCE | xargs realpath )"
-TICKETS_PATH="$BASHTICKETS_PATH/tickets"
-MILESTONES_PATH="$BASHTICKETS_PATH/milestones"
+  BASHTICKETS_PATH="$( dirname $BASH_SOURCE | xargs realpath )"
+  TICKETS_PATH="$BASHTICKETS_PATH/tickets"
+  MILESTONES_PATH="$BASHTICKETS_PATH/milestones"
 
 # Confirm validity of inputs
-MILESTONE="$1"
-ERRORS=0
+  MILESTONE="$1"
+  ERRORS=0
 
-if   test "${MILESTONE%.milestone}" = "0"
-then MILESTONE=""
-elif test -f "$MILESTONES_PATH/${MILESTONE%.milestone}.milestone"
-then :
-else echo "Input Error: No such milestone (${MILESTONE%.milestone}.milestone) exists in $MILESTONES_PATH"
-     ERRORS=$((ERRORS + 1))
-fi
+  if   test "${MILESTONE%.milestone}" = "0"
+  then MILESTONE=""
+  elif test -f "$MILESTONES_PATH/${MILESTONE%.milestone}.milestone"
+  then :
+  else echo "Input Error: No such milestone (${MILESTONE%.milestone}.milestone) exists in $MILESTONES_PATH"
+       ERRORS=$((ERRORS + 1))
+  fi
 
-if test "$ERRORS" -gt 0
-then echo "Encountered input errors. Aborting."
-     exit 1
-fi
+  if test "$ERRORS" -gt 0
+  then echo "Encountered input errors. Aborting."
+       exit 1
+  fi
 
-cd $TICKETS_PATH
+  cd $TICKETS_PATH
 
-MILESTONE_TICKETS=( $(egrep --color=never  -l "Milestone: $MILESTONE\$" *.ticket) )
+  MILESTONE_TICKETS=( $(egrep --color=never  -l "Milestone: $MILESTONE\$" *.ticket) )
 
-for  TICKET in "${MILESTONE_TICKETS[@]}"
-do   TICKETNAME="$(grep -l --color=never "Status: Closed" "$TICKET")"
-     TICKETSUMMARY="$(grep --color=never "Summary: " "$TICKET")"
-     if test -n "$TICKETNAME"
-     then echo "$TICKETNAME $TICKETSUMMARY"
-     fi
-done
+  for  TICKET in "${MILESTONE_TICKETS[@]}"
+  do   TICKETNAME="$(grep -l --color=never "Status: Closed" "$TICKET")"
+       TICKETSUMMARY="$(grep --color=never "Summary: " "$TICKET")"
+       if test -n "$TICKETNAME"
+       then echo "$TICKETNAME $TICKETSUMMARY"
+       fi
+  done
