bt init relies on built-in validation to detect valid repo first

diff --git a/share/utils/initialise_bashtickets_repository b/share/utils/initialise_bashtickets_repository
--- a/share/utils/initialise_bashtickets_repository
+++ b/share/utils/initialise_bashtickets_repository
@@ -5,11 +5,21 @@
 
 if     test $( ls -A | wc -l ) -eq 0   # empty directory detected
 
-then   if     touch .bashtickets.repo
+then   if     mkdir .bashtickets
 
        then   :
 
-       else   error "Error: Could not create '.bashtickets.repo' file in current directory."
+       else   error "Error: Could not create a '.bashtickets' subdirectory in the current directory."
+              error "       Please ensure you have the necessary permissions."
+              exit 1
+       fi
+
+
+       if   cp  "$BT_DOC_DIR/sample_config" ".bashtickets/config"
+
+       then :
+
+       else   error "Error: Could not create a 'config' file in the '.bashtickets' subdirectory."
               error "       Please ensure you have the necessary permissions."
               exit 1
        fi
@@ -34,7 +44,7 @@ then   if     touch .bashtickets.repo
 
        echo   "Bashtickets repository initialised successfully."
 
-elif   test -d tickets && test -d milestones && test -f .bashtickets.repo
+elif   "$BT_UTILS_DIR/is_valid_bashtickets_repository" 2> /dev/null
 
 then   error "Error: Current directory is already a valid bashtickets repository"
        error "       Aborting..."
