Apropriate aborting in new ticket and milestone if no edits detected

diff --git a/share/utils/new_milestone b/share/utils/new_milestone
--- a/share/utils/new_milestone
+++ b/share/utils/new_milestone
@@ -48,13 +48,23 @@
   DEFAULT_DEADLINE="$( get_default_milestone_deadline $DEFAULT_STARTDATE )"
   sed -i "s/Deadline: /Deadline: $DEFAULT_DEADLINE/" "${NEW_MILESTONE_FILE}"
 
+# Save current status of ticket before manual editing
+  UNEDITED_MILESTONE="$(cat $NEW_MILESTONE_FILE)"
+
 # Open resulting file in vim or nano for further editing, place cursor at Title field
   if   test $EDITOR = "vim"
   then vim '+cal cursor(2,16)' "${NEW_MILESTONE_FILE}"
   else nano +2,16 "${NEW_MILESTONE_FILE}"
   fi
 
-# Report successful creation of new ticket, mentioning number.
-  echo
-  echo "Milestone No. ${NEW_MILESTONE_NUM} created successfully"
-  echo
+  EDITED_MILESTONE="$(cat $NEW_MILESTONE_FILE)"
+
+  if   test "$UNEDITED_MILESTONE" = "$EDITED_MILESTONE"
+  then error "Error: No edits detected."
+       error "Aborting new milestone creation."
+       rm "$NEW_MILESTONE_FILE"
+       exit 1
+  else echo
+       echo "Milestone No. ${NEW_MILESTONE_NUM} created successfully"
+       echo
+  fi
diff --git a/share/utils/new_ticket b/share/utils/new_ticket
--- a/share/utils/new_ticket
+++ b/share/utils/new_ticket
@@ -49,20 +49,30 @@
 
 # Select a valid type:
   echo "Select a valid ticket type:"
+  declare -i REPLY   # The user's input is assigned to this variable; we want to ensure it only takes numeric values
   select TICKET_TYPE in "${TICKET_TYPES[@]}"   # TICKET_TYPES obtained from config
   do
-      sed -i "s/Type: /Type: $TICKET_TYPE/" "${NEW_TICKET_FILE}"
-      break
+      if   test $REPLY -gt 0 && test $REPLY -le ${#TICKET_TYPES[@]}
+      then sed -i "s/Type: /Type: $TICKET_TYPE/" "${NEW_TICKET_FILE}"
+           break
+      else error "Invalid selection, please chose a number between 1 and ${#TICKET_TYPES[@]}" && exit 1
+      fi
   done
+  declare +i REPLY
 
 # Select a valid priority:
   echo
   echo "Select a valid ticket priority"
+  declare -i REPLY   # The user's input is assigned to this variable; we want to ensure it only takes numeric values
   select TICKET_PRIORITY in "${TICKET_PRIORITY_LEVELS[@]}"   # TICKET_PRIORITY_LEVELS obtained from config
   do
-      sed -i "s/Priority: /Priority: ${TICKET_PRIORITY%% *}/" "${NEW_TICKET_FILE}"   # Remove everything in the priority string after the first space (i.e. the explanation of the priority level)
-      break
+      if   test $REPLY -gt 0 && test $REPLY -le ${#TICKET_PRIORITY_LEVELS[@]}
+      then sed -i "s/Priority: /Priority: ${TICKET_PRIORITY%% *}/" "${NEW_TICKET_FILE}"   # Remove everything in the priority string after the first space (i.e. the explanation of the priority level)
+           break
+      else error "Invalid selection, please chose a number between 1 and ${#TICKET_PRIORITY_LEVELS[@]}" && exit 1
+      fi
   done
+  declare +i REPLY
 
 # Set today's date
   TODAY=$(date +"%Y-%m-%d")
@@ -70,6 +80,9 @@
 
 # Declare status as Open
   sed -i "s/Status: /Status: Open/" "${NEW_TICKET_FILE}"
+
+# Save current status of ticket before manual editing
+  UNEDITED_TICKET="$(cat $NEW_TICKET_FILE)"
 
 # Open resulting file in the user's editor of choice, as detected by the
  # EDITOR environmental variable. This can be overriden per bashtickets
@@ -82,7 +95,14 @@
   else nano +2,14 "${NEW_TICKET_FILE}"
   fi
 
-# Report successful creation of new ticket, mentioning number.
-  echo
-  echo "Ticket No. ${NEW_TICKET_NUM} created successfully"
-  echo
+  EDITED_TICKET="$(cat $NEW_TICKET_FILE)"
+
+  if   test "$UNEDITED_TICKET" = "$EDITED_TICKET"
+  then error "Error: No edits detected."
+       error "Aborting new ticket creation."
+       rm "$NEW_TICKET_FILE"
+       exit 1
+  else echo
+       echo "Ticket No. ${NEW_TICKET_NUM} created successfully"
+       echo
+  fi
